name: Test Local Action
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run-local-action:
    env: 
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '24'

      - name: Build
        run: npm ci && npm run build

      - name: Run Local Action
        uses: ./

      - name: Smoketest VM Binary Exists
        run: vm --version
